### ISSUE TITLE
Which HIP Version Built On?

### ISSUE THREAD

**Issue by ronulman421** [Elfin-Jedi/Novum-Imperium#5]
What HIP version did you guys built this pack on? I understand that putting this all together was probably a mess, but I found that some files are outdated from the latest HIP (Frosty3). For example, in common/council_voting the files still point to a wrong "mazdakism" religion, when it should be "mazdaki", which Frosty3 fixed.

I think this could probably be because of the map mods, that were probably built off of an older HIP version. I understand that it would be a mess to see which one is outdated.

Another thing could be that some mod that was made for an older HIP version changed those council_voting files back to an outdated one. If so, disregard this, sorry for the mistake.

**Comment by Elfin-Jedi** [comment]
I actually didn't know that "mazdaki" was a change made by HIP. I have always used HIP as my base when modding.

I changed them to match Lux Invicta, though I actually like "religion_mazdaki" better than "religion_mazdakism" so I might just mass replace them all. I assume "zurvanist" vs. "zurvanism" is the same situation?

**Comment by ronulman421** [comment]
I see, I thought it was a bug. It's because I noticed that in the latest HIP there's a "mazdaki" religion in 00_religions, and in Novum Imperium the council_voting files (like 01_pragmatist_pattern) it points to a "mazdakism" religion. I thought it was a typo, but I went to see Novum Imperium's 00_religion and it seems the "mazdaki" religion entries were removed (only one "intermarry = "mazdakism" is left in khurmazta religion). It was probably removed by one of the Ancient Religion mods or some mod that changed the Zoroastrian religion group.

**Comment by Elfin-Jedi** [comment]
It is in 00_lux under religions. I recently added Lux Invicta's religion file and chose to use it as the base for religions. I then "updated" all the "mazdaki" references to "mazdakism" to match Lux Invicta. "Mazdakism" still exists, just in the lux file.

**Comment by ronulman421** [comment]
I see, my mistake. Anyway, love this mod and the hard work you guys put to it.
